image: Visual Studio 2017

platform:
  - x86
  - x64

configuration:
  - Release

for:
  - matrix:
      only:
        - platform: x64
    environment:
      ARCH: x64
  - matrix:
      only:
        - platform: x86
    environment:
      ARCH: Win32

before_build:
  - cmake .\Source\Native -G "Visual Studio 15 2017" -A %ARCH% -DENET_SHARED=1 -DCMAKE_BUILD_TYPE=Release -DENET_LZ4=1

build_script:
  - cmake --build . --config Release

artifacts:
  - path: 'Release\*.dll'
    name: Releases

deploy:
  provider: GitHub
  auth_token:
    secure: "LsT5P0KETM65BKOmRDmRX8Uqufkv1iu1G4aa1+rkeg50f9JYW7KnBscZpwmPqqte"
  artifact: /.*\.dll/
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
