image: Visual Studio 2017

platform:
  - x64
  - x86

configuration:
  - Release

for:
  - matrix:
      only:
        - platform: x64
    environment:
      - ARCH: x64
  - matrix:
      only:
        - platform: x86
    environment:
      - ARCH: Win32

before_build:
  - cmake .\Source\Native -G "Visual Studio 15 2017" -A x64 -DENET_SHARED=1 -DENET_TEST=1

build:
  project: $(APPVEYOR_BUILD_FOLDER)\$(APPVEYOR_PROJECT_NAME).sln

test_script:
  - '%APPVEYOR_BUILD_FOLDER%\%CONFIGURATION%\enet_test.exe'

artifacts:
  - path: 'Release\*.dll'
    name: Releases
