image: Visual Studio 2017

platform:
  - x86
  - x64

configuration:
  - Release

for:
  - matrix:
      only:
        - platform: x64
    environment:
      ARCH: x64
  - matrix:
      only:
        - platform: x86
    environment:
      ARCH: Win32

before_build:
  - cmake .\Source\Native -G "Visual Studio 15 2017" -A %ARCH% -DENET_SHARED=1

build_script:
  - cmake --build . --config Release

artifacts:
  - path: 'Release\*.dll'
    name: Releases
